# Generated by Django 2.1.2 on 2018-10-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181018_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
